apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: assignment2app
  labels:
    app: employees
selector:
    app: employees
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000