apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replicaset
  namespace: assignment2app
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: application-container
          image: 921348694553.dkr.ecr.us-east-1.amazonaws.com/assignment-application:v0.1
          ports:
            - containerPort: 8080
          env:
            - name: DBPORT
              value: "3306"
            - name: DBHOST
              value: "mysql-service.assignment2db.svc.cluster.local"
            - name: DBUSER
              value: root
            - name: DATABASE
              value: employees
            - name: DBPWD
              value: pw
            - name: APP_COLOR
              value: lime
          ports:
            - containerPort: 8080
             
